redis:
  host: redis:6379
  passwd: {redis_passwd}
  exts:
    maxIdle: 32
    idleTimeout: 240s
    connTimeout: 5s
    maxConnLifetime: 0s
    testOnBorrow: PING
  dbs:
    - 
      key: default
      db: 0
mysql:
  -
    key: default
    type: mysql
    host: mysql:3306
    user: {mysql_user}
    dbname: apps
    passwd: {mysql_passwd}
    debug: false
    exts:
      maxIdle: 10
  -
    key: minipro
    type: mysqlorm
    host: mysql:3306
    user: {mysql_user}
    dbname: apps
    passwd: {mysql_passwd}
    debug: false
    exts:
      maxIdle: 10