version: '3'
services:
  mysql:
    restart: always
    image: 'mysql:5.7'
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=apps
      - MYSQL_USER=joyousx
      - MYSQL_PASSWORD=123.456
      - MYSQL_ROOT_PASSWORD=saturn
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  redis:
    restart: always
    image: 'redis:5.0'
    ports:
      - '6379:6379'
    volumes:
      - /data/redis:/data #- ./redis.conf:/usr/local/etc/redis/redis.conf   挂载配置文件
    command: --requirepass '123.456'
    environment:
      - Debug=true

# external_links:
#   - container_name:apollo