version: '3'
services:
  mysql:
    # 指定容器名称后，该服务将无法进行扩展（scale），因为 Docker 不允许多个容器具有相同的名称。
    container_name: mysql.5.7 
    restart: always
    image: 'mysql:5.7'
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=apps
      - MYSQL_USER=joyousx
      - MYSQL_PASSWORD=123.456
      - MYSQL_ROOT_PASSWORD=saturn
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  redis:
    container_name: redis.5
    restart: always
    image: 'redis:5.0'
    ports:
      - '6379:6379'
    volumes:
      - /data/redis:/data
      #- ./redis.conf:/usr/local/etc/redis/redis.conf   挂载配置文件
    command: --requirepass '123.456'
    environment:
      - Debug=true

  nginx:
    depends_on:
      - mysql
      - redis 
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - redis
      - mysql
    volumes:
      - ./webs:/data/webs/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./crts/2_DomainName.key:/etc/nginx/2_DomainName.key:ro
      - ./crts/1_DomainName_bundle.crt:/etc/nginx/1_DomainName_bundle.crt:ro
    command: [nginx-debug, '-g', 'daemon off;']